[project]
name = "tg-spam-bot"
version = "0.1.0"
description = "Telegram bot for spam filtering"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiogram==3.10.0",
    "python-dotenv==1.0.1",
]
