name: CI for Telegram Spam Bot

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install UV
      run: |
        curl -sSf https://install.zshell.dev | bash -s -- -y
        export PATH=/home/runner/.local/bin:$PATH
        pip install uv
        
    - name: Install dependencies
      run: |
        export PATH=/home/runner/.local/bin:$PATH
        uv pip install pytest flake8 mypy
        uv sync
        
    - name: Run tests
      run: |
        export PATH=/home/runner/.local/bin:$PATH
        pytest test_*.py -v
        
    - name: Lint with flake8
      run: |
        export PATH=/home/runner/.local/bin:$PATH
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Type check with mypy
      run: |
        export PATH=/home/runner/.local/bin:$PATH
        mypy --ignore-missing-imports core/ models/ utils/
        
  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and export Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: tg_spam_bot:latest
        outputs: type=docker,dest=/tmp/tg_spam_bot.tar
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: tg_spam_bot
        path: /tmp/tg_spam_bot.tar
